config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - filter.format.rich_text
  module:
    - ckeditor
format: rich_text
editor: ckeditor
settings:
  toolbar:
    rows:
      -
        -
          name: Formatting
          items:
            - Bold
            - Italic
            - Strike
            - Superscript
            - Subscript
            - '-'
            - RemoveFormat
        -
          name: Linking
          items:
            - DrupalLink
            - DrupalUnlink
        -
          name: Lists
          items:
            - BulletedList
            - NumberedList
        -
          name: Media
          items:
            - Blockquote
            - Table
            - HorizontalRule
            - DrupalMediaLibrary
        -
          name: 'Block Formatting'
          items:
            - Format
        -
          name: Tools
          items:
            - ShowBlocks
            - DrupalFontAwesome
            - Source
        -
          name: 'WET Components'
          items:
            - footnotes
            - abbr
            - detail
            - panel
            - alert
        -
          name: WxT
          items:
            - Maximize
  plugins:
    language:
      language_list: un
    drupallink:
      linkit_enabled: true
      linkit_profile: default
    stylescombo:
      styles: ''
    codemirror:
      enable: true
      startupMode: wysiwyg
      mode: htmlmixed
      theme: monokai
      options:
        lineNumbers: true
        lineWrapping: true
        matchBrackets: true
        autoCloseTags: true
        autoCloseBrackets: true
        enableSearchTools: true
        enableCodeFolding: true
        enableCodeFormatting: true
        autoFormatOnStart: true
        autoFormatOnModeChange: true
        autoFormatOnUncomment: true
    tokenbrowser:
      token_types: {  }
image_upload:
  status: true
  scheme: public
  directory: inline-images
  max_size: ''
  max_dimensions:
    width: null
    height: null
