config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.embedded
    - core.entity_view_mode.media.full_width
    - core.entity_view_mode.media.large
    - core.entity_view_mode.media.medium
    - core.entity_view_mode.media.small
  module:
    - blazy
    - editor
    - footnotes
    - media
    - toc_filter
    - token_filter
    - wxt_ext_editor
name: 'Rich text'
format: rich_text
weight: 1
filters:
  filter_align:
    id: filter_align
    provider: filter
    status: true
    weight: -49
    settings: {  }
  filter_caption:
    id: filter_caption
    provider: filter
    status: true
    weight: -48
    settings: {  }
  filter_htmlcorrector:
    id: filter_htmlcorrector
    provider: filter
    status: true
    weight: -47
    settings: {  }
  editor_file_reference:
    id: editor_file_reference
    provider: editor
    status: true
    weight: -46
    settings: {  }
  filter_html:
    id: filter_html
    provider: filter
    status: true
    weight: -50
    settings:
      allowed_html: '<br> <p class="text-align-left text-align-center text-align-right text-align-justify"> <h2 id class="text-align-left text-align-center text-align-right text-align-justify"> <h3 id class> <h4 id class> <h5 id class="text-align-left text-align-center text-align-right text-align-justify"> <h6 id class="text-align-left text-align-center text-align-right text-align-justify"> <cite> <dl> <dt> <dd> <a hreflang href> <blockquote cite> <ul type> <ol type start> <img src alt data-entity-type data-entity-uuid data-align data-caption> <drupal-entity data-* title alt> <strong> <em> <u> <code class="language-*"> <pre class="text-align-left text-align-center text-align-right text-align-justify"> <s> <li> <hr> <table> <tr> <td rowspan colspan> <th rowspan colspan> <thead> <tbody> <tfoot> <caption> <drupal-media data-entity-type data-entity-uuid alt data-caption data-align> <details class> <summary> <div class> <section class> <header class>'
      filter_html_help: true
      filter_html_nofollow: false
  filter_autop:
    id: filter_autop
    provider: filter
    status: false
    weight: -43
    settings: {  }
  filter_html_escape:
    id: filter_html_escape
    provider: filter
    status: false
    weight: -44
    settings: {  }
  filter_html_image_secure:
    id: filter_html_image_secure
    provider: filter
    status: false
    weight: -41
    settings: {  }
  filter_url:
    id: filter_url
    provider: filter
    status: false
    weight: -42
    settings:
      filter_url_length: 72
  media_embed:
    id: media_embed
    provider: media
    status: true
    weight: -39
    settings:
      default_view_mode: embedded
      allowed_view_modes:
        default: default
        full_width: full_width
        large: large
        medium: medium
        small: small
      allowed_media_types: {  }
  blazy_filter:
    id: blazy_filter
    provider: blazy
    status: false
    weight: 3
    settings:
      media_switch: ''
      hybrid_style: ''
      box_style: ''
      box_caption: ''
      filter_tags:
        img: img
        iframe: iframe
      use_data_uri: '0'
  filter_footnotes:
    id: filter_footnotes
    provider: footnotes
    status: false
    weight: 0
    settings:
      footnotes_collapse: '0'
      footnotes_html: '0'
  toc_filter:
    id: toc_filter
    provider: toc_filter
    status: false
    weight: 0
    settings:
      type: default
      auto: ''
      block: '0'
      exclude_above: '0'
  token_filter:
    id: token_filter
    provider: token_filter
    status: false
    weight: 0
    settings:
      replace_empty: '0'
