name: tag
on:
  push:
    tags:
    - '*'

# Environment variables available to all jobs and steps in this workflow
env:
  COMPOSER_MEMORY_LIMIT: -1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup dependencies
      run: |
        git clone --branch 8.x https://github.com/drupalwxt/site-wxt.git
        cd site-wxt
        rm composer.lock

    - uses: statcan/actions/composer@master
      with:
        args: require drupalwxt/wxt:${GITHUB_REF#refs/tags/} --working-dir=./site-wxt

    - name: Build out the Drupal infrastructure
      run: |
        cd site-wxt
        git clone https://github.com/drupalwxt/docker-scaffold.git docker
        make build
        docker-compose -f docker-compose-ci.yml up -d
        docker ps -a
        sleep 10

    - name: Run installation and tests
      run: |
        cd site-wxt
        make drupal_install
        make drupal_migrate
        # Change ownership on html/core to allow files to be copied (see drupal_cs in Makefile)
        sudo chown -R $(id -u) html/core
        make test

    - name: Generate tarball
      run: |
        cd site-wxt
        ./tarball.sh ${${GITHUB_REF#refs/tags/}:3:1}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${GITHUB_REF#refs/tags/}
        release_name: ${GITHUB_REF#refs/tags/}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./wxt-8.x-${${GITHUB_REF#refs/tags/}:3:1}.tar.gz
        asset_name: wxt-8.x-${${GITHUB_REF#refs/tags/}:3:1}.tar.gz
        asset_content_type: application/tar+gzip

    - name: Checkout repos to update tags
      run: |
        git clone --branch 8.x https://github.com/drupalwxt/wxt-project.git
        git clone --branch master https://github.com/drupalwxt/helm-drupal.git
        git clone --branch master https://github.com/drupalwxt/terraform-containers-webapp-azure
        git clone --branch master https://github.com/drupalwxt/terraform-kubernetes-drupalwxt

    - name: Update tags for wxt-project
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "\"drupalwxt/wxt\": \"3.*.*\""
        replace: "\"drupalwxt/wxt\": \"${GITHUB_REF#refs/tags/}\""
        input: ".*"
        exclude: ".git/"
        include: "wxt-project/"

    - name: Update tags for helm-drupal
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "appVersion: 3.*.*"
        replace: "appVersion: ${GITHUB_REF#refs/tags/}"
        input: ".*"
        exclude: ".git/"
        include: "helm-drupal/"

    - name: Update tags for helm-drupal
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "tag: 3.*.*"
        replace: "tag: ${GITHUB_REF#refs/tags/}"
        input: ".*"
        exclude: ".git/"
        include: "helm-drupal/"

    - name: Update tags for terraform-containers-webapp-azure
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "image: drupalwxt/site-wxt:3.*.*"
        replace: "image: drupalwxt/site-wxt:${GITHUB_REF#refs/tags/}"
        input: ".*"
        exclude: ".git/"
        include: "terraform-kubernetes-drupalwxt/"

    - name: Update tags for terraform-kubernetes-drupalwxt
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "tag: 3.*.*"
        replace: "tag: ${GITHUB_REF#refs/tags/}"
        input: ".*"
        exclude: ".git/"
        include: "terraform-kubernetes-drupalwxt/"

    - name: Push to site-wxt the latest build sha
      run: |
        cd site-wxt
        composer install
        git add .
        git commit -m "Update to latest version of WxT ${GITHUB_REF#refs/tags/}"
        git push origin 8.x

    - name: Push to wxt-project the latest tags
      run: |
        cd wxt-project
        git add .
        git commit -m "Update to latest version of WxT ${GITHUB_REF#refs/tags/}"
        git push origin 8.x

    - name: Push to helm-drupal the latest tags
      run: |
        cd helm-drupal
        git add .
        git commit -m "Update to latest version of WxT ${GITHUB_REF#refs/tags/}"
        git push origin master

    - name: Push to terraform-containers-webapp-azure the latest tags
      run: |
        cd terraform-containers-webapp-azure
        git add .
        git commit -m "Update to latest version of WxT ${GITHUB_REF#refs/tags/}"
        git push origin master

    - name: Push to terraform-kubernetes-drupalwxt the latest tags
      run: |
        cd terraform-kubernetes-drupalwxt
        git add .
        git commit -m "Update to latest version of WxT ${GITHUB_REF#refs/tags/}"
        git push origin master

      - name: Repository Dispatch to website
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: drupalwxt/website
          event-type: wxt-tagged
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

    # Connect to Container registry
    - uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    # Container build and push to a Container registry
    - run: |
        docker tag site-wxt_web:latest drupalwxt/site-wxt:${GITHUB_REF#refs/tags/}
        docker tag site-wxt_nginx:latest drupalwxt/site-wxt:${GITHUB_REF#refs/tags/}-nginx
        docker push drupalwxt/site-wxt:${GITHUB_REF#refs/tags/}
        docker push drupalwxt/site-wxt:${GITHUB_REF#refs/tags/}-nginx
